version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:node14.15.0-chrome96-ff94
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          name: Building the app for testing
          command: yarn build
      - run:
          name: Running cypress
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/