version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      # the Docker image with Cypress dependencies
      - image: cypress/browsers:node14.15.0-chrome96-ff94
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-npm-deps-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v2-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.cache
      - run:
          name: Building the app for testing
          command: yarn build
      - run:
          name: Running cypress
          command: yarn test
      - persist_to_workspace:
          root: ~/app
          paths: .
      - attach_workspace:
          at: ~/app
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/app/.npmrc
      - run:
          name: Publish package
          command: npm publish
  